# Deploy a guest from a template
# # No reconfiguration of the destination guest is done at this stage, a reconfigure would be needed to adjust memory/cpu etc..
---
-  name: Create VMware guest from Template
   hosts: localhost
   connection: local
   gather_facts: False

   vars:
      
      guest: LiamTestFromTemplate
      osid:  rhel6_64Guest
      num_cpus: 4
      memory_mb: 4096
      nic1: Vlan984-203.13.128.64/27-Srvc-RPxy-IZ-EF
      nic2: Vlan152-161.43.32.0/24-vmnetwork
      
      datacenter: CHOC
      datastore: f2_v031_eca04_02
      disk1_size: 10
      hostname: infprdvire082.optus.com.au #would migrate to suitable host automatically after poweron

      notes: Created By Ansible

   tasks:
    - name: Deploy guest from template
      vsphere_guest:
         vcenter_hostname: '{{vcenter_hostname}}'
         username: '{{username}}'
         password: '{{password}}'
         guest: '{{guest}}'  #guest name
         from_template: yes
         template_src: LiamtestVM
         #state: "powered_on"  
         cluster: CHOC

         esxi:
            datacenter: '{{datacenter}}'
            hostname: '{{hostname}}'
         validate_certs: no #ssl validate

         #with_items: '{{serverlist}}'
         #vm_cdrom:
         #  type: "iso"
         #  iso_path: "DatastoreName/cd-image.iso"
         #vm_floppy:
         #  type: "image"
         #  image_path: "DatastoreName/floppy-image.flp"
